version: '3.7'
services:

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Recife
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker_from_zero_to_mastery_java
    ports:
      - "3309:3306"
    networks:
      - udemy-network
        
  docker-from-zero-to-mastery-java:
    image: docker-from-zero-to-mastery-java
    restart: always
    build:
      context: .
      dockerfile: app/Dockerfile
    working_dir: /app
    environment: 
      TZ: America/Recife
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - udemy-network

networks:
  udemy-network:

